### ISSUE TITLE
Error 500 with Form Requests

### ISSUE THREAD

**Issue by enzonotario** [jadjoubran/laravel5-angular-material-starter#226]
Hi, i have a problem using Form Requests only when the route is:

```
$api->version('v1', ['namespace' => 'API'], function ($api) {
    $api->resource('expedientes', 'ExpedienteController');
});
```

But no when the route is:

```
Route::post('expedientes', 'API\ExpedienteController@store');
```

and if the route is Route::post('api/expedientes', 'API\ExpedienteController@store'); the error 500 persists

My ExpedienteController@store is:

```
public function store(StoreExpedienteRequest $request)
    {
        $input = $request->all();

        $expediente = $this->expedienteRepository->create([$input]);

        return $this->response->item($expediente, new ExpedienteTransformer);
    }
```

My StoreExpedienteRequest is:

```
<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class StoreExpedienteRequest extends Request
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'numero' => 'requir',
        ];
    }
}
```

My App\Http\Request is:

```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;
use Validator;

abstract class Request extends FormRequest
{
    protected $forceJsonResponse = true;

    public function response(array $errors)
    {
        if ($this->forceJsonResponse || $this->ajax() || $this->wantsJson()) {
            return new JsonResponse($errors, 422);
        }

        return $this->redirector->to($this->getRedirectUrl())
            ->withInput($this->except($this->dontFlash))
            ->withErrors($errors, $this->errorBag);
    }

    // Custom validations
    public function validator()
    {
        $v = Validator::make($this->input(), $this->rules(), $this->messages(), $this->attributes());

        if (method_exists($this, 'moreValidation')) {
            $this->moreValidation($v);
        }

        return $v;
    }
}
```

Can someone help me please?

Thanks!!

**Comment by jadjoubran** [comment]
Hi @enzonotario 
Add the following entry to your `.env` file:
`API_DEBUG=true`
And paste the output of the error you see when calling the API

**Comment by enzonotario** [comment]
Hi, my .env has API_DEBUG=true
but in POSTMAN it only returns
`
{
  "message": "500 Internal Server Error",
  "status_code": 500
}
`

**Comment by jadjoubran** [comment]
Do you have your `APP_DEBUG=true` enabled?

**Comment by enzonotario** [comment]
Ahhhhhhhhhhhh, sorry!! i have APP_DEBUG=true, no API_DEBUG=true... my bad..
it returns:

```
{
  "message": "500 Internal Server Error",
  "status_code": 500,
  "debug": {
    "line": 97,
    "file": "/var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Foundation/Http/FormRequest.php",
    "class": "Illuminate\\Http\\Exception\\HttpResponseException",
    "trace": [
      "#0 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(25): Illuminate\\Foundation\\Http\\FormRequest->failedValidation(Object(Illuminate\\Validation\\Validator))",
      "#1 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(44): Illuminate\\Foundation\\Http\\FormRequest->validate()",
      "#2 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Container/Container.php(1035): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->Illuminate\\Foundation\\Providers\\{closure}(Object(App\\Http\\Requests\\StoreExpedienteRequest), Object(Illuminate\\Foundation\\Application))",
      "#3 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Container/Container.php(1000): Illuminate\\Container\\Container->fireCallbackArray(Object(App\\Http\\Requests\\StoreExpedienteRequest), Array)",
      "#4 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\\Container\\Container->fireResolvingCallbacks('App\\Http\\Reques...', Object(App\\Http\\Requests\\StoreExpedienteRequest))",
      "#5 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\\Container\\Container->make('App\\Http\\Reques...', Array)",
      "#6 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(85): Illuminate\\Foundation\\Application->make('App\\Http\\Reques...')",
      "#7 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(59): Illuminate\\Routing\\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array, Array)",
      "#8 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(42): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))",
      "#9 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(144): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(App\\Http\\Controllers\\API\\ExpedienteController), 'store')",
      "#10 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\\Routing\\ControllerDispatcher->call(Object(App\\Http\\Controllers\\API\\ExpedienteController), Object(Illuminate\\Routing\\Route), 'store')",
      "#11 [internal function]: Illuminate\\Routing\\ControllerDispatcher->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#12 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#13 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#14 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#15 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#16 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\\Routing\\ControllerDispatcher->callWithinStack(Object(App\\Http\\Controllers\\API\\ExpedienteController), Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request), 'store')",
      "#17 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request), 'App\\Http\\Contro...', 'store')",
      "#18 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\\Routing\\Route->runController(Object(Dingo\\Api\\Http\\Request))",
      "#19 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\\Routing\\Route->run(Object(Dingo\\Api\\Http\\Request))",
      "#20 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#21 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#22 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#23 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#24 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#25 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
      "#26 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
      "#27 /var/www/pps/expedientes/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#28 /var/www/pps/expedientes/vendor/dingo/api/src/Routing/Router.php(559): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
      "#29 /var/www/pps/expedientes/vendor/dingo/api/src/Http/Middleware/Request.php(112): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#30 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#31 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#32 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#33 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#34 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#35 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#36 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
      "#37 /var/www/pps/expedientes/vendor/dingo/api/src/Http/Middleware/Request.php(113): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#38 /var/www/pps/expedientes/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
      "#39 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
      "#40 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
      "#41 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
      "#42 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
      "#43 [internal function]: Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
      "#44 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
      "#45 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#46 /var/www/pps/expedientes/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
      "#47 /var/www/pps/expedientes/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
      "#48 {main}"
    ]
  }
}
```

**Comment by jadjoubran** [comment]
It means that you have an error in file `FormRequest.php` on line 97
This should guide to find the issue

**Comment by enzonotario** [comment]
yes.. but i dont understand why..

```
95 protected function failedValidation(Validator $validator)
96     {
97         throw new HttpResponseException($this->response(
98             $this->formatErrors($validator)
99         ));
100     }
```

**Comment by enzonotario** [comment]
it works with Route::post(...) but no with $api->resourece / $api->post ... it is that i don't understand

**Comment by jadjoubran** [comment]
Have you implemented [this](https://github.com/dingo/api/wiki/Errors-And-Error-Responses#form-requests)?
It's already fixed in this repo, but I'm not aware of how you're trying to fix it

**Comment by enzonotario** [comment]
well.. it works with:

```
use Dingo\Api\Exception\ResourceException;
use Illuminate\Contracts\Validation\Validator;
...
protected function failedValidation(Validator $validator)
    {
        throw new ResourceException('Invalid request', $validator->getMessageBag());
    }
```

Thanks!

**Comment by jadjoubran** [comment]
awesome!

**Comment by phanthanhquoc** [comment]
it's worked for me too. great!
it seems that because we used Dingo\Api so it conflicted with Response Exception of laravel. So we should override this by using Dingo Resource exception.

I think so, Does it make sense of this?

**Comment by jadjoubran** [comment]
@phanthanhquoc yep, I've also had to override the validate method in the `controller.php` because of Dingo API

**Comment by brickgale** [comment]
@enzonotario where did you override `failedValidation` function? on request or controller? *I tried on request. It gave me what I wanted. Thanks!

**Comment by enzonotario** [comment]
Hi!, yes, I did override it in requests. But the new version of this starter does not use dingo, another thing that I do is:
```
protected function failedValidation(Validator $validator)
    {
        throw new \Exception(json_encode([
            'message' => 'Invalid request',
            'status_code' => 422,
            'errors' => $validator->getMessageBag()
            ]), 1);
    }
```

Or in the render method of app/Exceptsions/Handler.php:
```
if ($exception instanceof ValidationException && $this->isApiRoute($request)) {
            return response()->json([
                'message' => 'Invalid request',
                'errors' => $exception->validator->getMessageBag()
                ], 422);
        } 
```

I don't know if it is the good way of do it, but it works for me.

SORRY FOR MY ENGLISH!.
