### ISSUE TITLE
Fresh Install but 404 (Not Found)

### ISSUE THREAD

**Issue by dkat101** [jadjoubran/laravel5-angular-material-starter#259]
I followed the guide but when I launch the starter app, nothing appears in the browser and the console shows the following.

GET http://mockup.app:8000/js/partials.js 
GET http://mockup.app:8000/css/app.css 
GET http://mockup.app:8000/js/app.js 
GET http://mockup.app:8000/css/app.css 
GET http://mockup.app:8000/js/partials.js 
GET http://mockup.app:8000/js/app.js 
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.3/$injector/nomod?p0=app
    at http://mockup.app:8000/js/vendor.js:68:12
    at http://mockup.app:8000/js/vendor.js:2034:17
    at ensure (http://mockup.app:8000/js/vendor.js:1958:38)
    at module (http://mockup.app:8000/js/vendor.js:2032:14)
    at http://mockup.app:8000/js/vendor.js:4524:22
    at forEach (http://mockup.app:8000/js/vendor.js:321:20)
    at loadModules (http://mockup.app:8000/js/vendor.js:4508:5)
    at createInjector (http://mockup.app:8000/js/vendor.js:4430:19)
    at doBootstrap (http://mockup.app:8000/js/vendor.js:1710:20)
    at bootstrap (http://mockup.app:8000/js/vendor.js:1731:12)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=app&p1=Error%3A%20%…20bootstrap%20(http%3A%2F%2Fmockup.app%3A8000%2Fjs%2Fvendor.js%3A1731%3A12)

**Comment by jadjoubran** [comment]
Hi @dkat101
Did you run `gulp`?

**Comment by dkat101** [comment]
yes i did

**Comment by jadjoubran** [comment]
Can you please show me a screenshot of your chrome console?

**Comment by dkat101** [comment]
this is the current output of gulp:

vagrant@homestead:~/laravel/mockup$ gulp
[19:53:45] Using gulpfile ~/laravel/mockup/gulpfile.js
[19:53:45] Starting 'default'...
[19:53:45] Starting 'bower-js'...
[19:53:45] Finished 'default' after 387 ms
[19:53:48] gulp-notify: [Laravel Elixir]  
[19:53:48] gulp-notify: [Laravel Elixir]  
[19:53:48] Finished 'bower-js' after 3.24 s
[19:53:48] Starting 'bower-css'...
[19:53:49] gulp-notify: [Laravel Elixir]  
[19:53:49] gulp-notify: [Laravel Elixir]  
[19:53:49] Finished 'bower-css' after 583 ms
[19:53:49] Starting 'angular in ./angular/'...

**Comment by jadjoubran** [comment]
Okay and a screenshot of the chrome console please

**Comment by dkat101** [comment]
![log](https://cloud.githubusercontent.com/assets/7871064/14583325/2ca75848-0427-11e6-84d2-03b6de298de1.png)

**Comment by dkat101** [comment]
Sorry, its working now.

I "vagrant ssh" into the virtual machine and run "gulp" and this was the output:

vagrant@homestead:~/laravel/mockup$ gulp
[19:53:45] Using gulpfile ~/laravel/mockup/gulpfile.js
[19:53:45] Starting 'default'...
[19:53:45] Starting 'bower-js'...
[19:53:45] Finished 'default' after 387 ms
[19:53:48] gulp-notify: [Laravel Elixir]  
[19:53:48] gulp-notify: [Laravel Elixir]  
[19:53:48] Finished 'bower-js' after 3.24 s
[19:53:48] Starting 'bower-css'...
[19:53:49] gulp-notify: [Laravel Elixir]  
[19:53:49] gulp-notify: [Laravel Elixir]  
[19:53:49] Finished 'bower-css' after 583 ms
[19:53:49] Starting 'angular in ./angular/'...
[19:57:18] Version: webpack 1.13.0
 Asset     Size  Chunks             Chunk Names
app.js  12.8 kB       0  [emitted]  main
[19:57:18] gulp-notify: [Laravel Elixir]  
[19:57:18] Finished 'angular in ./angular/' after 3.48 min
[19:57:18] Starting 'ngHtml2Js'...
[19:57:19] Finished 'ngHtml2Js' after 659 ms
[19:57:19] Starting 'less'...

Fetching Less Source Files...
- ./angular/*_/_.less

Saving To...
- public/css/app.css

[19:57:47] gulp-notify: [Laravel Elixir] Less Compiled!
[19:57:47] Finished 'less' after 28 s

When I tested again in the browser, all worked.

**Comment by jadjoubran** [comment]
Okay great :smile:
