### ISSUE TITLE
Cache bugout

### ISSUE THREAD

**Issue by michaelbdavidson7** [jadjoubran/laravel5-angular-material-starter#298]
Hi,
I pulled the repo and got started, and went and tested the register then the login functions. upon attempting to login, the app exploded with a big cache-related error out of the box. this was with no changes made by me. Also it won't forget my cached data no matter how hard i reset my browser window. please let me know how i can fix this. thanks. 

``` javascript
4angular.js:13550 Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Bearer <br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"errors":false,"data":{"user":{"name":"asdfasdf","email":"asdfasdf@example.com","updated_at":"2016-05-03 11:23:21","created_at":"2016-05-03 11:23:21","id":1},"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDAwXC9hcGlcL2F1dGhcL3JlZ2lzdGVyIiwiaWF0IjoxNDYyMjc0NjAxLCJleHAiOjE0NjIyNzgyMDEsIm5iZiI6MTQ2MjI3NDYwMSwianRpIjoiZDYyNWVkYzFiMTBkYmRkZWRkZGI0MzEwYzNhODc3Y2YifQ.ixCZFwk1zxb73RDvby-TL3OT0VhoYb7qCU6tkFrSWhI"}}' is not a valid HTTP header field value.
    at Error (native)
    at http://localhost:8000/build/js/vendor-51717ab6e9.js:11690:17
    at forEach (http://localhost:8000/build/js/vendor-51717ab6e9.js:336:20)
    at http://localhost:8000/build/js/vendor-51717ab6e9.js:11688:7
    at sendReq (http://localhost:8000/build/js/vendor-51717ab6e9.js:11517:9)
    at serverRequest (http://localhost:8000/build/js/vendor-51717ab6e9.js:11227:16)
    at processQueue (http://localhost:8000/build/js/vendor-51717ab6e9.js:15961:28)
    at http://localhost:8000/build/js/vendor-51717ab6e9.js:15977:27
    at Scope.$eval (http://localhost:8000/build/js/vendor-51717ab6e9.js:17229:28)
    at Scope.$digest (http://localhost:8000/build/js/vendor-51717ab6e9.js:17045:31)(anonymous function) @ angular.js:13550(anonymous function) @ angular.js:10225processQueue @ angular.js:15969(anonymous function) @ angular.js:15977Scope.$eval @ angular.js:17229Scope.$digest @ angular.js:17045Scope.$apply @ angular.js:17337bootstrapApply @ angular.js:1749invoke @ angular.js:4665doBootstrap @ angular.js:1747bootstrap @ angular.js:1767angularInit @ angular.js:1652(anonymous function) @ angular.js:30863trigger @ angular.js:3166defaultHandlerWrapper @ angular.js:3456eventHandler @ angular.js:3444
4angular.js:13550 Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50`
'''
```

**Comment by flick36** [comment]
Hi, first of all if you could please use 3 backticks and a new line to format your code ```

The first thing i see is that it's a php error, not the starter fault, just open your `php.ini` file and uncomment the line `always_populate_raw_post_data` and set it to `-1`

[Here](http://stackoverflow.com/questions/26261001/warning-about-http-raw-post-data-being-deprecated)

although i have it commented and it's working fine, have you tried download the starter again?

The token it's no eliminated when you close the browser, you have to delete the cookie or wait the time especified in the `config.php` file to the token to expire

**Comment by michaelbdavidson7** [comment]
your fix worked. sorry, i didnt realize that that line was commented out I only realized that when you mentiond it.
i also fixed the formatting of this question. thanks for your help. i love the framework!
