### ISSUE TITLE
Errors with fresh installation with wampServer

### ISSUE THREAD

**Issue by Neo-89** [jadjoubran/laravel5-angular-material-starter#307]
Hi,

when I install your project and run locally with WamServer (i tried with php5.6 and php7), I get in console two errors:

```
Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'Bearer <br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"message":"422 Unprocessable Entity","errors":{"email":["The email field is required."],"password":["The password field is required."]},"status_code":422}' is not a valid HTTP header field value.
    at Error (native)
    at http://localhost:8000/build/js/vendor-82b01a1c34.js:11690:17
    at forEach (http://localhost:8000/build/js/vendor-82b01a1c34.js:336:20)
    at http://localhost:8000/build/js/vendor-82b01a1c34.js:11688:7
    at sendReq (http://localhost:8000/build/js/vendor-82b01a1c34.js:11517:9)
    at serverRequest (http://localhost:8000/build/js/vendor-82b01a1c34.js:11227:16)
    at processQueue (http://localhost:8000/build/js/vendor-82b01a1c34.js:15961:28)
    at http://localhost:8000/build/js/vendor-82b01a1c34.js:15977:27
    at Scope.$eval (http://localhost:8000/build/js/vendor-82b01a1c34.js:17229:28)
    at Scope.$digest (http://localhost:8000/build/js/vendor-82b01a1c34.js:17045:31)
```

and:

```
Broken interceptor detected: Config object not supplied in rejection:
 https://github.com/chieffancypants/angular-loading-bar/pull/50
```

I tried to change php.ini, google also didn't help.

**Comment by flick36** [comment]
https://github.com/jadjoubran/laravel5-angular-material-starter/issues/298

**Comment by Neo-89** [comment]
Hi, 
thanks for link, but I noticed that this problem is only on Chrome browser and this is connected with CORS with localhost. I tried to change php.ini but it didn't work. Anyway, I work with Firefox and all is fine :)
