### ISSUE TITLE
errors when running gulp command

### ISSUE THREAD

**Issue by llstarscreamll** [jadjoubran/laravel5-angular-material-starter#380]
Hii!! Really nice package... Thanks for this big effort!!
- **I'm submitting a ...**
- [x] bug report
- **Provide information & explanation**
  Have a fresh install of project, run the command `gulp && gulp watch` and get this errors:

``` shell
$ gulp
(node:15706) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[04:15:11] Using gulpfile /var/www/test/gulpfile.js
[04:15:11] Starting 'default'...
[04:15:11] Starting 'bower-js'...
[04:15:11] Finished 'default' after 22 ms
[04:15:12] gulp-notify: [Laravel Elixir]  
[04:15:12] gulp-notify: [Laravel Elixir]  
[04:15:12] Finished 'bower-js' after 899 ms
[04:15:12] Starting 'bower-css'...
[04:15:12] gulp-notify: [Laravel Elixir]  
[04:15:12] gulp-notify: [Laravel Elixir]  
[04:15:12] Finished 'bower-css' after 203 ms
[04:15:12] Starting 'angular in ./angular/'...
[04:15:13] Version: webpack 1.13.1
 Asset     Size  Chunks             Chunk Names
app.js  32.8 kB       0  [emitted]  main
[04:15:13] gulp-notify: [Laravel Elixir]  
[04:15:13] Finished 'angular in ./angular/' after 1.18 s
[04:15:13] Starting 'ng-html-js'...
[04:15:13] 'ng-html-js' errored after 225 ms
[04:15:13] Error: EPERM: operation not permitted, chmod '/var/www/test/public/js/partials.js'
  at Error (native)

[04:15:13] Error in plugin 'run-sequence(ng-html-js)'
Message:
    EPERM: operation not permitted, chmod '/var/www/test/public/js/partials.js'
Details:
    errno: -1
    code: EPERM
    syscall: chmod
    path: /var/www/test/public/js/partials.js
Stack:
Error: EPERM: operation not permitted, chmod '/var/www/test/public/js/partials.js'
  at Error (native)
```
- **Got code samples?**
  I haven't code samples, is fresh install, I used the commands specified on the docs for this installation...
- **Laravel & Angular version:** 3.3

**Comment by jadjoubran** [comment]
Hi @llstarscreamll 
What versions of node and npm are you running? `node -v` `npm -v`

**Comment by llstarscreamll** [comment]
Hi, mi node and npm versions, files and folders permissions and OS version:

``` shell
$ node -v
v6.2.0
johan@johan-ubuntu: /var/www/test
$ npm -v
3.9.2
johan@johan-ubuntu: /var/www/test
$ gulp -v
[12:04:54] CLI version 3.9.1
[12:04:54] Local version 3.9.1
johan@johan-ubuntu: /var/www/test
$ ls -l
total 272
drwxrwxr-x  10 www-data www-data   4096 Jul 15 06:09 angular
drwxrwxr-x  10 www-data www-data   4096 Jul 15 06:09 app
-rw-rw-r--   1 www-data www-data   1646 Jul 15 06:09 artisan
drwxrwxr-x   3 www-data www-data   4096 Jul 15 06:09 bootstrap
drwxrwxr-x  13 www-data www-data   4096 Aug  3 02:34 bower_components
-rw-rw-r--   1 www-data www-data    456 Jul 15 06:09 bower.json
-rw-rw-r--   1 www-data www-data   1757 Jul 15 06:09 composer.json
-rw-rw-r--   1 www-data www-data 137134 Jul 15 06:09 composer.lock
drwxrwxr-x   2 www-data www-data   4096 Jul 15 06:09 config
drwxrwxr-x   5 www-data www-data   4096 Jul 15 06:09 database
-rw-rw-r--   1 www-data www-data    183 Jul 15 06:09 elixir.json
-rw-rw-r--   1 www-data www-data   1837 Aug  3 04:11 gulpfile.js
-rw-rw-r--   1 www-data www-data    876 Jul 15 06:09 karma.conf.js
-rw-rw-r--   1 www-data www-data   1079 Jul 15 06:09 LICENSE
drwxrwxr-x 986 www-data www-data  36864 Aug  3 03:53 node_modules
-rw-rw-r--   1 johan    johan      1602 Aug  3 03:53 package.json
-rw-rw-r--   1 www-data www-data    976 Jul 15 06:09 phpunit.xml
-rw-rw-r--   1 www-data www-data    750 Jul 15 06:09 precache-config.json
drwxrwxr-x   7 www-data www-data   4096 Aug  3 02:37 public
-rw-rw-r--   1 www-data www-data   2408 Jul 15 06:09 readme.md
drwxrwxr-x   4 www-data www-data   4096 Jul 15 06:09 resources
-rw-rw-r--   1 www-data www-data    546 Jul 15 06:09 server.php
drwxrwxr-x   5 www-data www-data   4096 Jul 15 06:09 storage
drwxrwxr-x   2 www-data www-data   4096 Jul 15 06:09 tasks
drwxrwxr-x   3 www-data www-data   4096 Jul 15 06:09 tests
drwxrwxr-x  36 www-data www-data   4096 Aug  3 02:28 vendor
-rw-rw-r--   1 www-data www-data    349 Jul 15 06:09 webpack.config.js
johan@johan-ubuntu: /var/www/test
$ ls -l public/
total 96
drwxrwxr-x 4 www-data www-data  4096 Aug  3 02:37 build
drwxrwxr-x 2 www-data www-data  4096 Aug  3 02:37 css
-rw-rw-r-- 1 www-data www-data 32038 Jul 15 06:09 favicon.ico
drwxrwxr-x 2 www-data www-data  4096 Jul 15 06:09 fonts
drwxrwxr-x 3 www-data www-data  4096 Jul 15 06:09 img
-rw-rw-r-- 1 www-data www-data  1766 Jul 15 06:09 index.php
drwxrwxr-x 2 www-data www-data  4096 Aug  3 02:36 js
-rw-rw-r-- 1 www-data www-data   322 Jul 15 06:09 manifest.json
-rw-rw-r-- 1 www-data www-data    24 Jul 15 06:09 robots.txt
-rw-rw-r-- 1 www-data www-data 28377 Aug  3 02:37 service-worker.js
-rw-rw-r-- 1 www-data www-data   914 Jul 15 06:09 web.config
johan@johan-ubuntu: /var/www/test
$ ls -l public/js/
total 10304
-rw-rw-r-- 1 www-data www-data   33607 Aug  3 04:15 app.js
-rw-rw-r-- 1 www-data www-data 3339264 Aug  3 02:36 final.js
-rw-rw-r-- 1 www-data www-data   17118 Aug  3 04:15 partials.js
-rw-rw-r-- 1 www-data www-data 3287892 Aug  3 04:15 vendor.js
-rw-rw-r-- 1 www-data www-data 3858752 Aug  3 04:15 vendor.js.map
johan@johan-ubuntu: /var/www/test
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```

**Comment by llstarscreamll** [comment]
The issue is related to the files/folders permission, I reinstalled the project and files/folders are owned by my user `johan` and `gulp` command runs fine, but when I open the browser nothing is shown, when change the owner to the web server I am see the page correctly on the browser but the `gulp` command doesn't work again...

When I run `gulp && gulp watch` get this error (without change file/folders owner, the owner is my user):

``` shell
[14:04:44] Finished 'version' after 63 ms
[14:04:44] Starting 'generate-service-worker'...
Total precache size is about 4.26 MB for 15 resources.
[14:04:44] Finished 'generate-service-worker' after 25 ms
(node:7802) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[14:04:45] Using gulpfile /var/www/test/gulpfile.js
[14:04:45] Starting 'watch'...
[14:04:45] 'watch' errored after 17 ms
[14:04:45] Error: watch /var/www/test/angular/app/components/app-header/ ENOSPC
  at exports._errnoException (util.js:953:11)
  at FSWatcher.start (fs.js:1423:19)
  at Object.fs.watch (fs.js:1450:11)
  at Gaze._watchDir (/var/www/test/node_modules/gaze/lib/gaze.js:289:30)
  at /var/www/test/node_modules/gaze/lib/gaze.js:358:10
  at iterate (/var/www/test/node_modules/gaze/lib/helper.js:52:5)
  at Object.forEachSeries (/var/www/test/node_modules/gaze/lib/helper.js:66:3)
  at Gaze._initWatched (/var/www/test/node_modules/gaze/lib/gaze.js:354:10)
  at Gaze.add (/var/www/test/node_modules/gaze/lib/gaze.js:177:8)
  at new Gaze (/var/www/test/node_modules/gaze/lib/gaze.js:74:10)
  at gaze (/var/www/test/node_modules/gaze/lib/gaze.js:86:10)
  at Object.module.exports [as watch] (/var/www/test/node_modules/glob-watcher/index.js:12:17)
  at Gulp.watch (/var/www/test/node_modules/gulp/index.js:40:14)
  at /var/www/test/node_modules/laravel-elixir/tasks/watch.js:40:18
  at Array.forEach (native)
  at Gulp.<anonymous> (/var/www/test/node_modules/laravel-elixir/tasks/watch.js:38:35)
  at module.exports (/var/www/test/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/var/www/test/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/test/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/test/node_modules/orchestrator/index.js:134:8)
  at /home/johan/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js:129:20
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Function.Module.runMain (module.js:577:11)
  at startup (node.js:160:18)
  at node.js:449:3
```

**Comment by jadjoubran** [comment]
normally this happens if you've used npm install with sudo before..
maybe you've installed gulp by doing sudo npm install?

**Comment by llstarscreamll** [comment]
no, I don't install with sudo, justo normal like you say on docs, if helps, I put my command line session here:

``` bash
johan@johan-ubuntu: /var/www
$ composer create-project jadjoubran/laravel5-angular-material-starter test --prefer-dist
johan@johan-ubuntu: /var/www
$ cd test
johan@johan-ubuntu: /var/www/test
$ ls -l
total 232
drwxrwxr-x 10 johan johan   4096 Jul 15 06:09 angular
drwxrwxr-x 10 johan johan   4096 Jul 15 06:09 app
-rwxr-xr-x  1 johan johan   1646 Jul 15 06:09 artisan
drwxrwxr-x  3 johan johan   4096 Jul 15 06:09 bootstrap
-rw-rw-r--  1 johan johan    456 Jul 15 06:09 bower.json
-rw-rw-r--  1 johan johan   1757 Jul 15 06:09 composer.json
-rw-rw-r--  1 johan johan 137134 Jul 15 06:09 composer.lock
drwxrwxr-x  2 johan johan   4096 Jul 15 06:09 config
drwxrwxr-x  5 johan johan   4096 Jul 15 06:09 database
-rw-rw-r--  1 johan johan    183 Jul 15 06:09 elixir.json
-rw-rw-r--  1 johan johan   1805 Jul 15 06:09 gulpfile.js
-rw-rw-r--  1 johan johan    876 Jul 15 06:09 karma.conf.js
-rw-rw-r--  1 johan johan   1079 Jul 15 06:09 LICENSE
-rw-rw-r--  1 johan johan   1576 Jul 15 06:09 package.json
-rw-rw-r--  1 johan johan    976 Jul 15 06:09 phpunit.xml
-rw-rw-r--  1 johan johan    750 Jul 15 06:09 precache-config.json
drwxrwxr-x  4 johan johan   4096 Jul 15 06:09 public
-rw-rw-r--  1 johan johan   2408 Jul 15 06:09 readme.md
drwxrwxr-x  4 johan johan   4096 Jul 15 06:09 resources
-rw-rw-r--  1 johan johan    546 Jul 15 06:09 server.php
drwxrwxr-x  5 johan johan   4096 Jul 15 06:09 storage
drwxrwxr-x  2 johan johan   4096 Jul 15 06:09 tasks
drwxrwxr-x  3 johan johan   4096 Jul 15 06:09 tests
drwxrwxr-x 36 johan johan   4096 Aug  7 00:47 vendor
-rw-rw-r--  1 johan johan    349 Jul 15 06:09 webpack.config.js
johan@johan-ubuntu: /var/www/test
$ npm install -g gulp bower
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/home/johan/.nvm/versions/node/v6.2.0/bin/bower -> /home/johan/.nvm/versions/node/v6.2.0/lib/node_modules/bower/bin/bower
/home/johan/.nvm/versions/node/v6.2.0/bin/gulp -> /home/johan/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js
/home/johan/.nvm/versions/node/v6.2.0/lib
├── bower@1.7.9 
└─┬ gulp@3.9.1 
  └─┬ liftoff@2.3.0
    └─┬ findup-sync@0.4.2
      └─┬ micromatch@2.3.11
        └─┬ kind-of@3.0.4
          └── is-buffer@1.1.4 

johan@johan-ubuntu: /var/www/test
$ npm install
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> phantomjs-prebuilt@2.1.10 install /var/www/test/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [=======================================-] 98%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /var/www/test/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1470549163895/phantomjs-2.1.1-linux-x86_64 -> /var/www/test/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /var/www/test/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> node-sass@3.8.0 install /var/www/test/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /var/www/test/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.8.0 postinstall /var/www/test/node_modules/node-sass
> node scripts/build.js

"/var/www/test/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
/var/www/test

#### Node packages installed here!!

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /karma-browserify/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
johan@johan-ubuntu: /var/www/test
$ php artisan migrate
Nothing to migrate.
johan@johan-ubuntu: /var/www/test
$ gulp
(node:24135) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[00:53:48] Using gulpfile /var/www/test/gulpfile.js
[00:53:48] Starting 'default'...
[00:53:48] Starting 'bower-js'...
[00:53:48] 'bower-js' errored after 814 μs
[00:53:48] Error: Bower components directory does not exist at /var/www/test/bower_components
  at Error (native)
  at module.exports (/var/www/test/node_modules/main-bower-files/lib/index.js:76:17)
  at .definition (/var/www/test/tasks/bower.task.js:38:19)
  at Task.run (/var/www/test/node_modules/laravel-elixir/Task.js:94:17)
  at Gulp.<anonymous> (/var/www/test/node_modules/laravel-elixir/index.js:89:52)
  at module.exports (/var/www/test/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/var/www/test/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/test/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/test/node_modules/orchestrator/index.js:134:8)
  at runNextSet (/var/www/test/node_modules/run-sequence/index.js:86:16)
  at runSequence (/var/www/test/node_modules/run-sequence/index.js:97:2)
  at Gulp.<anonymous> (/var/www/test/node_modules/laravel-elixir/tasks/default.js:18:16)
  at module.exports (/var/www/test/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/var/www/test/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/test/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/test/node_modules/orchestrator/index.js:134:8)
  at /home/johan/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js:129:20
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Function.Module.runMain (module.js:577:11)
  at startup (node.js:160:18)
  at node.js:449:3

[00:53:48] Error in plugin 'run-sequence(bower-js)'
Message:
    Bower components directory does not exist at /var/www/test/bower_components
Stack:
Error: Bower components directory does not exist at /var/www/test/bower_components
  at Error (native)
  at module.exports (/var/www/test/node_modules/main-bower-files/lib/index.js:76:17)
  at .definition (/var/www/test/tasks/bower.task.js:38:19)
  at Task.run (/var/www/test/node_modules/laravel-elixir/Task.js:94:17)
  at Gulp.<anonymous> (/var/www/test/node_modules/laravel-elixir/index.js:89:52)
  at module.exports (/var/www/test/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/var/www/test/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/test/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/test/node_modules/orchestrator/index.js:134:8)
  at runNextSet (/var/www/test/node_modules/run-sequence/index.js:86:16)
  at runSequence (/var/www/test/node_modules/run-sequence/index.js:97:2)
  at Gulp.<anonymous> (/var/www/test/node_modules/laravel-elixir/tasks/default.js:18:16)
  at module.exports (/var/www/test/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/var/www/test/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/test/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/test/node_modules/orchestrator/index.js:134:8)
  at /home/johan/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js:129:20
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Function.Module.runMain (module.js:577:11)
  at startup (node.js:160:18)
  at node.js:449:3

[00:53:48] Finished 'default' after 3.94 ms
johan@johan-ubuntu: /var/www/test
$ bower install
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#~1.5
bower cached        https://github.com/angular-ui/angular-ui-router-bower.git#1.0.0-beta.1
bower validate      1.0.0-beta.1 against https://github.com/angular-ui/angular-ui-router-bower.git#~1.0.0-alpha.3
bower cached        https://github.com/chieffancypants/angular-loading-bar.git#0.9.0
bower validate      0.9.0 against https://github.com/chieffancypants/angular-loading-bar.git#~0.9.0
bower cached        https://github.com/sahat/satellizer.git#0.14.1
bower validate      0.14.1 against https://github.com/sahat/satellizer.git#^0.14.0
bower cached        https://github.com/mgonto/restangular.git#1.5.2
bower validate      1.5.2 against https://github.com/mgonto/restangular.git#~1.5.2
bower cached        https://github.com/angular/bower-material.git#1.0.9
bower validate      1.0.9 against https://github.com/angular/bower-material.git#~1.0.8
bower cached        https://github.com/gsklee/ngStorage.git#0.3.11
bower validate      0.3.11 against https://github.com/gsklee/ngStorage.git#~0.3.10
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#>= 1.2.0
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#^1.2.9
bower cached        https://github.com/angular/bower-angular.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular.git#>=1.3.x
bower cached        https://github.com/lodash/lodash.git#4.14.1
bower validate      4.14.1 against https://github.com/lodash/lodash.git#>=1.3.0
bower cached        https://github.com/angular/bower-angular-aria.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular-aria.git#^1.4.8
bower cached        https://github.com/angular/bower-angular-messages.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular-messages.git#^1.4.8
bower cached        https://github.com/angular/bower-angular-animate.git#1.5.8
bower validate      1.5.8 against https://github.com/angular/bower-angular-animate.git#^1.4.8
bower install       angular-ui-router#1.0.0-beta.1
bower install       angular-loading-bar#0.9.0
bower install       restangular#1.5.2
bower install       satellizer#0.14.1
bower install       angular#1.5.8
bower install       ngstorage#0.3.11
bower install       lodash#4.14.1
bower install       angular-material#1.0.9
bower install       angular-aria#1.5.8
bower install       angular-messages#1.5.8
bower install       angular-animate#1.5.8

angular-ui-router#1.0.0-beta.1 bower_components/angular-ui-router
└── angular#1.5.8

angular-loading-bar#0.9.0 bower_components/angular-loading-bar
└── angular#1.5.8

restangular#1.5.2 bower_components/restangular
├── angular#1.5.8
└── lodash#4.14.1

satellizer#0.14.1 bower_components/satellizer
└── angular#1.5.8

angular#1.5.8 bower_components/angular

ngstorage#0.3.11 bower_components/ngstorage
└── angular#1.5.8

lodash#4.14.1 bower_components/lodash

angular-material#1.0.9 bower_components/angular-material
├── angular#1.5.8
├── angular-animate#1.5.8
├── angular-aria#1.5.8
└── angular-messages#1.5.8

angular-aria#1.5.8 bower_components/angular-aria
└── angular#1.5.8

angular-messages#1.5.8 bower_components/angular-messages
└── angular#1.5.8

angular-animate#1.5.8 bower_components/angular-animate
└── angular#1.5.8
johan@johan-ubuntu: /var/www/test
$ gulp && gulp watch
(node:24314) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[00:54:36] Using gulpfile /var/www/test/gulpfile.js
[00:54:36] Starting 'default'...
[00:54:36] Starting 'bower-js'...
[00:54:36] Finished 'default' after 20 ms
[00:54:37] gulp-notify: [Laravel Elixir]  
[00:54:37] gulp-notify: [Laravel Elixir]  
[00:54:37] Finished 'bower-js' after 840 ms
[00:54:37] Starting 'bower-css'...
[00:54:37] gulp-notify: [Laravel Elixir]  
[00:54:37] gulp-notify: [Laravel Elixir]  
[00:54:37] Finished 'bower-css' after 197 ms
[00:54:37] Starting 'angular in ./angular/'...
[00:54:39] Version: webpack 1.13.1
 Asset     Size  Chunks             Chunk Names
app.js  32.8 kB       0  [emitted]  main
[00:54:39] gulp-notify: [Laravel Elixir]  
[00:54:39] Finished 'angular in ./angular/' after 1.6 s
[00:54:39] Starting 'ng-html-js'...
[00:54:39] Finished 'ng-html-js' after 264 ms
[00:54:39] Starting 'concat-scripts'...
[00:54:39] Finished 'concat-scripts' after 12 ms
[00:54:39] Starting 'sass'...

Fetching Sass Source Files...
   - ./angular/**/*.scss
   - !angular/critical.scss


Saving To...
   - public/css/app.css

[00:54:39] gulp-notify: [Laravel Elixir] Sass Compiled!
[00:54:39] Finished 'sass' after 271 ms
[00:54:39] Starting 'sass'...

Fetching Sass Source Files...
   - ./angular/critical.scss


Saving To...
   - public/css/critical.css

[00:54:39] gulp-notify: [Laravel Elixir] Sass Compiled!
[00:54:39] Finished 'sass' after 26 ms
[00:54:39] Starting 'styles'...

Fetching Styles Source Files...
   - ./public/css/vendor.css
   - ./public/css/app.css


Saving To...
   - ./public/css/final.css

[00:54:39] gulp-notify: [Laravel Elixir] Stylesheets Merged!
[00:54:39] Finished 'styles' after 71 ms
[00:54:39] Starting 'version'...

Fetching Version Source Files...
   - public/js/final.js
   - public/css/final.css


Saving To...
   - public/build

[00:54:39] Finished 'version' after 62 ms
[00:54:39] Starting 'generate-service-worker'...
Total precache size is about 4.26 MB for 15 resources.
[00:54:39] Finished 'generate-service-worker' after 28 ms
(node:24373) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[00:54:41] Using gulpfile /var/www/test/gulpfile.js
[00:54:41] Starting 'watch'...
[00:54:41] 'watch' errored after 17 ms
[00:54:41] Error: watch /var/www/test/angular/app/components/app-header/ ENOSPC
  at exports._errnoException (util.js:953:11)
  at FSWatcher.start (fs.js:1423:19)
  at Object.fs.watch (fs.js:1450:11)
  at Gaze._watchDir (/var/www/test/node_modules/gaze/lib/gaze.js:289:30)
  at /var/www/test/node_modules/gaze/lib/gaze.js:358:10
  at iterate (/var/www/test/node_modules/gaze/lib/helper.js:52:5)
  at Object.forEachSeries (/var/www/test/node_modules/gaze/lib/helper.js:66:3)
  at Gaze._initWatched (/var/www/test/node_modules/gaze/lib/gaze.js:354:10)
  at Gaze.add (/var/www/test/node_modules/gaze/lib/gaze.js:177:8)
  at new Gaze (/var/www/test/node_modules/gaze/lib/gaze.js:74:10)
  at gaze (/var/www/test/node_modules/gaze/lib/gaze.js:86:10)
  at Object.module.exports [as watch] (/var/www/test/node_modules/glob-watcher/index.js:12:17)
  at Gulp.watch (/var/www/test/node_modules/gulp/index.js:40:14)
  at /var/www/test/node_modules/laravel-elixir/tasks/watch.js:40:18
  at Array.forEach (native)
  at Gulp.<anonymous> (/var/www/test/node_modules/laravel-elixir/tasks/watch.js:38:35)
  at module.exports (/var/www/test/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/var/www/test/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/var/www/test/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/var/www/test/node_modules/orchestrator/index.js:134:8)
  at /home/johan/.nvm/versions/node/v6.2.0/lib/node_modules/gulp/bin/gulp.js:129:20
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Function.Module.runMain (module.js:577:11)
  at startup (node.js:160:18)
  at node.js:449:3

johan@johan-ubuntu: /var/www/test
$ 
```

**Comment by jadjoubran** [comment]
@llstarscreamll if you're on ubuntu it might be related to this issue:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

> ```
> The system has a limit to how many files can be watched by a user. You can run out of watches pretty quickly if you have Grunt running with other programs like Dropbox. This command increases the maximum amount of watches a user can have
> ```

(also applies to gulp)

**Comment by llstarscreamll** [comment]
The SO second answer did the trick, but I had to change the owner on the public folder:

``` bash
$ sudo chown johan public/*/*
$ sudo chown johan public/*/*/*
```

The `gulp && gulp watch` command works now. Thank you for your time and help.
Cheers.

**Comment by jadjoubran** [comment]
Great thanks!
