### ISSUE TITLE
erro na instalação no commando gulp

### ISSUE THREAD

**Issue by Marcosul** [jadjoubran/laravel5-angular-material-starter#478]
* **I'm submitting a instalation problem.**
Following the installation instructions, to try to execute the "gulp" command, the console shows the error below:

Please, can you guide me how to solve it?

Thank you!
Marco
```

module.js:328
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/umbrela.club/gulpfile.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
root@ubuntu-512mb-nyc3-01:/var/www/umbrela.club# gulp
module.js:328
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/umbrela.club/gulpfile.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by Marcosul** [comment]
fixed!
It was necessary to install laravel-elixir globally and that's it.
