### ISSUE TITLE
Problem while "installing"

### ISSUE THREAD

**Issue by prigal** [jadjoubran/laravel5-angular-material-starter#7]
Hi,

I follow the steps you wrote : 
- git clone git@github.com:jadjoubran/laravel5-angular-material-starter.git : OK
- npm install -g gulp bower  : OK
- composer install  : OK
- npm install  : OK
- bower install  : OK with a choice, I choose 3)

``` sh
Unable to find a suitable version for angular, please choose one:
    1) angular#1.3 which resolved to 1.3.15 and is required by laravel5-angular-material-starter
    2) angular#^1.3.0 || >1.4.0-beta.0 which resolved to 1.3.15 and is required by angular-material#0.9.4
    3) angular#>= 1.0.8 which resolved to 1.3.15 and is required by angular-ui-router#0.2.15
    4) angular#1.4.0 which resolved to 1.4.0 and is required by angular-animate#1.4.0, angular-aria#1.4.0
    5) angular#~1.x which resolved to 1.4.0 and is required by restangular#1.5.1
    6) angular#>=1.0.8 which resolved to 1.4.0 and is required by ngstorage#0.3.4
```
- gulp : KO

``` sh
MacBook-Pro-de-Pierre-2:project1 pierrerigal$ gulp
[11:19:49] Using gulpfile ~/Projets/project1/gulpfile.js
[11:19:49] Starting 'default'...
[11:19:49] Starting 'bower-css'...
[11:19:49] Starting 'bower-js'...
[11:19:49] Finished 'default' after 63 ms
[11:20:10] Finished 'bower-js' after 21 s
[11:20:10] Finished 'bower-css' after 21 s
[11:20:10] Starting 'bower'...
[11:20:10] Finished 'bower' after 15 μs
[11:20:10] Starting 'angular in angular/'...
[11:20:11] Finished 'angular in angular/' after 308 ms
[11:20:11] Starting 'less'...
[11:20:11] Running Less: resources/assets/less/../../../angular/**/*.less
[11:20:12] Finished 'less' after 1.07 s
[11:20:12] Starting 'copy'...
[11:20:12] Finished 'copy' after 5.12 ms
[11:20:12] Starting 'styles'...
[11:20:12] Merging: resources/.tmp/**/*.css

events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: /Users/pierrerigal/Projets/project1/resources/.tmp/all.css: Unexpected token (1:0)
> 1 | .Dashboard-Container li {
    | ^
  2 |   line-height: 26px;
  3 | }
  4 | 
    at Parser.pp.raise (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseExprAtom (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:393:12)
    at Parser.parseExprAtom (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:624:24)
    at Parser.pp.parseExprSubscripts (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseExpression (/Users/pierrerigal/Projets/project1/node_modules/laravel-elixir/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/expression.js:81:19)
```

Why ? :) 

Thanks.

Notes : 
- First time with L5, Gulp, Angular
- Familiar with L4, Composer, Bower, Grunt

**Comment by jadjoubran** [comment]
Thanks for posting here!
Can you please try running gulp again and let me know.

If you're still getting the error, open `angular/app/dashboard/dashboard.less` and comment out the code and run grunt again. Let me know if this works for you.

Thanks

**Comment by prigal** [comment]
Hi,

Gulp still hangs with same error.

I pull to get last bower.json, then 'bower update', no more angular question, then I try to gulp again, same error.

Then I try to comment, I get an error on the next CSS file : 

``` sh
SyntaxError: /Users/pierrerigal/Projets/project1/resources/.tmp/all.css: Unexpected token (5:0)
  3 | }*/
  4 | 
> 5 | .Footer-Container {
    | ^
  6 |   background-color: #ececec;
  7 |   padding: 30px;
  8 |   position: fixed;
```

I also had to comment landing.less to get gulp to complete ^^

So what's going wrong here ? (I'm on mac, yosemite, node v0.12.4, npm v2.10.1)

Thanks for your help.

**Comment by prigal** [comment]
One more thing : Laravel5 DebugBar is not loaded at the bottom of the page. (Same problem on your demo app on ghpages)

**Comment by jadjoubran** [comment]
Unfortunately I'm not able to reproduce the issue even with a fresh installation..
Can you try clearing your npm cache and then running a new installation?
To clear your npm cache run `npm cache clear`

Regarding debugbar, it seems the new laravel installer is not creating a `.env` file, so just copy the `.env.example` file to `.env` and you'll start seeing Debugbar (because it requires `APP_DEBUG=true`)

But I can never make it work on ghpages because it's static pages, so it's just the front-end section of the repository!

Let me know if you were able to fix it

**Comment by jadjoubran** [comment]
Any updates?
If it's still not working I can try setting it up on my friend's mac

**Comment by jadjoubran** [comment]
Feel free to reopen if you this issue is still there

**Comment by prigal** [comment]
Hope this response will not reopen it now, but I didn't have any time to
test since last time, too much work on an other project.
I'll tell you when I'll give an other try.

Le lun. 1 juin 2015 à 18:55, Jad Joubran notifications@github.com a
écrit :

**Comment by jadjoubran** [comment]
Don't worry about it!
Awaiting your feedback
Thanks
