### ISSUE TITLE
Windows + Homestead

### ISSUE THREAD

**Issue by pdcmoreira** [jadjoubran/laravel5-angular-material-starter#72]
Hello there,

Has anyone tried to install this in homestead, in a Windows host?

I've tried `npm install -g gulp bower`, gave me permission error.
Tried `sudo npm install -g gulp bower`, it seems like it worked.

`composer create-project jadjoubran/laravel5-angular-material-starter myapp --prefer-dist` worked fine (I usually create new laravel projects this way).

It all falls apart when I try to do `npm install`:

```
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path /home/vagrant/projects/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/home/vagrant/projects/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path npm-debug.log.4ad20327e9e1aba39170203d795ee830
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.4ad20327e9e1aba39170203d795ee830' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/projects/npm-debug.log
vagrant@homestead:~/projects$ cd moviebox/
vagrant@homestead:~/projects/moviebox$ clear
vagrant@homestead:~/projects/moviebox$ npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN optional dep failed, continuing fsevents@1.0.2
npm ERR! tar.unpack untar error /home/vagrant/.npm/normalize-package-data/2.3.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm WARN optional dep failed, continuing fsevents@1.0.2
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/normalize-package-data/2.3.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/normalize-package-data/2.3.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/normalize-package-data/2.3.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/base64-arraybuffer/0.1.2/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/request/2.11.4/package.tgz
-
> utf-8-validate@1.2.1 install /home/vagrant/projects/moviebox/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/vagrant/projects/moviebox/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/vagrant/projects/moviebox/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
npm ERR! tar.unpack untar error /home/vagrant/.npm/nan/2.0.9/package.tgz
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

> bufferutil@1.2.1 install /home/vagrant/projects/moviebox/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/vagrant/projects/moviebox/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/home/vagrant/projects/moviebox/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
npm ERR! tar.unpack untar error /home/vagrant/.npm/validate-npm-package-license/3.0.1/package.tgz
npm ERR! tar.unpack untar error /home/vagrant/.npm/hosted-git-info/2.1.4/package.tgz
npm WARN optional dep failed, continuing source-map@0.2.0
npm WARN optional dep failed, continuing mime@1.3.4
npm WARN optional dep failed, continuing image-size@0.3.5
npm WARN optional dep failed, continuing errno@0.1.4
npm WARN optional dep failed, continuing mkdirp@0.5.1
npm WARN optional dep failed, continuing request@2.64.0
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path ../supports-color/cli.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../supports-color/cli.js' -> '/home/vagrant/projects/moviebox/node_modules/gulp-concat-sourcemap/node_modules/gulp-util/node_modules/chalk/node_modules/.bin/supports-color'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path npm-debug.log.6f64392f9f7d0503e8c9d73cf02b6470
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.6f64392f9f7d0503e8c9d73cf02b6470' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/projects/moviebox/npm-debug.log
```

Can't get past this!

Any help?

**Comment by Bodom78** [comment]
Seeing the "npm ERR! tar.unpack" errors and being on Windows I would guess it's the windows folder limit being exceeded by nodes crazy nesting.

Please see [https://github.com/jadjoubran/laravel5-angular-material-starter/issues/61#issuecomment-145564131](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/61#issuecomment-145564131)

**Comment by masterpowers** [comment]
Mine i Got this Error

```
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing fsevents@^1.0.0
npm WARN optional dep failed, continuing fsevents@^1.0.0
npm WARN optional dep failed, continuing fsevents@^1.0.0
|


> spawn-sync@1.0.13 postinstall C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

/


> utf-8-validate@1.2.1 install C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-
8-validate
> node-gyp rebuild

/
  rebuild ) npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) |de_modules\utf-8-validate>if -
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
\


> bufferutil@1.2.1 install C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferut
il
> node-gyp rebuild

-
C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_confi
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> utf-8-validate@1.2.1 install C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cli
ent\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_module
s\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\w
s\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1


> bufferutil@1.2.1 install C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\
node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

|
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) modules\ws\node_modul
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\w
s\node_modules\bufferutil
gyp ERR! node -v v0.12.7
 ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1


> node-sass@3.3.3 install C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/win32-x64-14_binding.node": getaddrinfo EAI_AGAIN
npm WARN optional dep failed, continuing bufferutil@1.2.1

> node-sass@3.3.3 postinstall C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild -
-verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Andrew Galang\\Code\\rfnbeta\\node_modules\\laravel-elixir\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.0.3
gyp info using node@0.12.7 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:73:28)

gyp verb `which` failed     at E (C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:76:29)

gyp verb `which` failed     at C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:84:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python2 [Error: not found: python2]
verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:73:28)

gyp verb `which` failed     at E (C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:76:29)

gyp verb `which` failed     at C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:84:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python [Error: not found: python]
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andrew Galang\\Code\\rfnbeta\\node_modules\\laravel-elixir\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\node-gyp\
\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Andrew Galang\Code\rfnbeta\node_modules\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\Andrew Galang\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, rename 'C:\Users\Andrew Galang\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Users\Andrew Galang\AppData\Roaming\npm-cache\inherits\2.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\Andrew Galang\\AppData\\Roaming\\npm-cache\\inherits\\2.0.1\\package\\package.json',
npm ERR!   parent: 'readable-stream' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by masterpowers** [comment]
trying to solve it with this
https://github.com/jadjoubran/laravel5-angular-material-starter/issues/61#issuecomment-145564131

ill post back if it fixes the problem

**Comment by BIGbuu** [comment]
@masterpowers open your eyes and read:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

setup the python

**Comment by masterpowers** [comment]
frankly i really dont know anything at python 
when i run npm install on vagrant its not throwing that error
maybe its already included there
but in my local machine its not
maybe thats the reason its throwing that error, 
thanks for informing but i really dont want to add pyton in my local machine
let see what will happen ill update this post also,
if i really need to install python locally if all else fails

**Comment by masterpowers** [comment]
the command i run on my local is npm install --no-bin-links

and that gives that error above.

if things went wrong in vagrant ill install python locally

**Comment by masterpowers** [comment]
hmmf i got this error when installing in vagrant
using command npm install

```
npm WARN EPACKAGEJSON /home/vagrant/Code/rfnbeta No repository field.
npm WARN EPACKAGEJSON /home/vagrant/Code/rfnbeta No license field.
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/home/vagrant/npm-global/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v3.3.5
npm ERR! path /home/vagrant/Code/rfnbeta/node_modules/.recast.DELETE
npm ERR! code EPERM
npm ERR! errno 50

npm ERR! Error: EPERM, rename '/home/vagrant/Code/rfnbeta/node_modules/.recast.D
ELETE'
npm ERR!  { [Error: EPERM, rename '/home/vagrant/Code/rfnbeta/node_modules/.reca
st.DELETE']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/home/vagrant/Code/rfnbeta/node_modules/.recast.DELETE' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/home/vagrant/npm-global/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v3.3.5
npm ERR! path npm-debug.log.97835dfeb93ecc71349b291fe24befed
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.97835dfeb93ecc71349b291fe24befed'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/rfnbeta/npm-debug.log
vagrant@homestead:~/Code/rfnbeta$ gulp

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/Code/rfnbeta/gulpfile.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by masterpowers** [comment]
i did install python on my local, 
then use npm install --no-bin-links
got this error though

```
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andrew Galang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.5

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrew Galang\Code\rfnbeta\npm-debug.log
```

but i can run gulp  , Does this mean im OK now or Not?

```
C:\Users\Andrew Galang\Code\rfnbeta>gulp
[17:22:34] Using gulpfile ~\Code\rfnbeta\gulpfile.js
[17:22:42] Starting 'default'...
[17:22:42] Starting 'bower-js'...
[17:22:42] Finished 'default' after 101 ms
[17:22:44] gulp-notify: [Laravel Elixir]
[17:22:44] gulp-notify: [Laravel Elixir]
[17:22:44] Finished 'bower-js' after 2.85 s
[17:22:44] Starting 'bower-css'...
[17:22:45] gulp-notify: [Laravel Elixir]
[17:22:45] gulp-notify: [Laravel Elixir]
[17:22:45] Finished 'bower-css' after 379 ms
[17:22:45] Starting 'angular in ./angular/'...
[17:22:46] gulp-notify: [Laravel Elixir]
[17:22:46] Finished 'angular in ./angular/' after 1.54 s
[17:22:46] Starting 'less'...

Fetching Less Source Files...
   - ./angular/**/*.less


Saving To...
   - public\css\app.css

[17:22:48] gulp-notify: [Laravel Elixir] Less Compiled!
[17:22:48] Finished 'less' after 1.69 s
[17:22:48] Starting 'copy'...

Fetching Copy Source Files...
   - ./angular/app/**/*.html


Saving To...
   - public/views/app/

[17:22:48] Finished 'copy' after 185 ms
[17:22:48] Starting 'copy'...

Fetching Copy Source Files...
   - ./angular/directives/**/*.html


Saving To...
   - public/views/directives/

[17:22:48] Finished 'copy' after 32 ms
[17:22:48] Starting 'copy'...

Fetching Copy Source Files...
   - ./angular/dialogs/**/*.html


Saving To...
   - public/views/dialogs/

[17:22:48] Finished 'copy' after 45 ms
[17:22:48] Starting 'phpUnit'...

Fetching PhpUnit Source Files...
   - tests/**/*Test.php

[17:22:48]

       *** Debug Cmd: .\vendor\bin\phpunit --colors --debug -c phpunit.xml ***

210
[17:22:48] '.\vendor\bin\phpunit' is not recognized as an internal or external command,
operable program or batch file.

[17:22:48] { [Error: Command failed: C:\Windows\system32\cmd.exe /s /c ".\vendor\bin\phpunit --colors --debug -c phpunit.xml"
'.\vendor\bin\phpunit' is not recognized as an internal or external command,
operable program or batch file.
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c ".\\vendor\\bin\\phpunit --colors --debug -c phpunit.xml"' }
[17:22:48] gulp-notify: [Red!] Your phpUnit tests failed!
[17:22:48] Finished 'phpUnit' after 131 ms
```

**Comment by ptondereau** [comment]
Hello @masterpowers 

First, you need to choose where you'll develop (between Vagrant + Windows Host or Windows only).

If you choose Vagrant's option, please update your Vagrant installation to the lastest version (currently 1.7.4). Then download a pre-packaged box with [PhpPuppet](https://puphpet.com/) (check install nodejs) or [Laravel Homestead](http://laravel.com/docs/5.1/homestead) 

Next, apply the first patch provided in issue #61 and run `vagrant up` where you've put your vagrant files.

Then, ensure your version of node is >= 4.1.1 and npm >= 3.3.5 (`npm -v` `node -v`)

Finaly, follow all others next steps in #61 .

**Comment by jadjoubran** [comment]
Closing this for now - feel free to re-open/comment if the issue persists
